code/src/LeafletProvider/Shape/AbstractPolyshape.ts, code/src/LeafletProvider/Shape/AbstractProviderShape.ts, code/src/LeafletProvider/Shape/Circle.ts, code/src/LeafletProvider/Shape/Factory.ts, code/src/LeafletProvider/Shape/Polygon.ts, code/src/LeafletProvider/Shape/Polyline.ts, code/src/LeafletProvider/Shape/Rectangle.ts, code/src/OSFramework/Shape/AbstractShape.ts
This PR is for RGRIDT-1032: [Maps] Leaflet Integration - Shapes [Shape implementation + logic - part 3]
* Leaflet Integration (parity feature to the existing Google Maps Shapes features).
* Created all the logic regarding shapes and abstracts (just like we have for the google provider):
* AbstractShape (OSFramework) ← AbstractProviderShape (LeafletProvider) ←AbstractPolyshape ← **Polyline**
* AbstractShape (OSFramework) ← AbstractProviderShape (LeafletProvider) ←AbstractPolyshape ← **Polygon**
* AbstractShape (OSFramework) ← AbstractProviderShape (LeafletProvider) ← **Circle**
* AbstractShape (OSFramework) ← AbstractProviderShape (LeafletProvider) ← **Rectangle**
* Lint clean up + GoogleProvider AbstractProviderShape fixed some variables and methods names
* Created the ShapeFactory on the …
=> RGRIDT-1032: [Maps] Leaflet Integration - Shapes [Shape implementation + logic - part 3]

code/package.json, code/src/LeafletProvider/Constants/Directions/DirectionsProvider.ts, code/src/LeafletProvider/Constants/Directions/TravelModes.ts, code/src/LeafletProvider/Features/FeatureBuilder.ts
This PR is for RGRIDT-1027: [Maps] Leaflet Integration - Set directions
* Leaflet Integration (parity feature to the existing Google Maps setDirections API)
* The wanted directions are shown on the Map when using "Provider" = Leaflet. 
* Added the leaflet-routing-machine into the package.json (devDependencies)
* Added Enum for the Name of the service that provides the routing mechanisms
* Added Enum for the TravelModes that each provider allows using
* Enabled the _makeDirections on the FeatureBuilder for the LeafletMap
=> RGRIDT-1027: [Maps] Leaflet Integration - Set directions [Part 1 - 1st Configs for Directions]

code/src/MapAPI/DrawingToolsManager.ts, code/src/MapAPI/FileLayerManager.Events.ts, code/src/MapAPI/FileLayerManager.ts, code/src/MapAPI/HeatmapLayerManager.ts, code/src/OSFramework/Enum/Feature.ts, code/src/OSFramework/Helper/ValidateFeatureProvider.ts
This PR is for RGRIDT-1108: [Maps] Add warning message to map blocks still incompatible with Leaflet
* We needed to add warning messages to map blocks still incompatible with Leaflet, like the Heatmap or File Layer, so our developers know it is not yet implemented.
* Added a new method that is responsible for checking if the feature is valid or not for the specific provider. This means it will check if the feature is already implemented or not. [temporary method]
=> RGRIDT-1108: [Maps] Add warning message to map blocks still incompatible with Leaflet

code/src/GoogleProvider/Features/Directions.ts, code/src/OSFramework/OSStructures/Directions.ts
This PR is for RGRDIT-1027: Bug on Google Provider setDirections [BUG]
* Google Provider changed the way it was doing the routes. Now it doesn't need to parse the waypoints because they are already parsed once they get into the setRoute() method
* Removed the JSON.parse from the method.
=> RGRDIT-1027: Bug on Google Provider setDirections [BUG]

code/src/GoogleProvider/Shape/AbstractProviderShape.ts, code/src/LeafletProvider/Shape/AbstractProviderShape.ts
This PR is for BugFixing V1.6.0 - Shape Events fix [Part 1]
* When Leaflet Shapes were introduced, the code for the setShapeEvents method was also cleaned up, which ended up with the removal of a part that was relevant for other events besides the special/custom events.
* Readded the logic that was deleted
Test Name | Test steps
-- | --
Polyline dragEnd Event | 1.Set the event "dragend" to the Polyline shape<br>2.Set the Allow Drag to True for the Polyline shape3.Drag and drop the shape into another position<br>Expected: A new feedback message should appear with the text "Changes occurred on Map -> MyMap, Shape -> Polyline, after triggering the event -> dragend"
Polygon dragEnd Event | 1.Set the event "dragend" to the Polygon shape<br>2.Set the Allow Drag to True for the Polygon …
=> BugFixing V1.6.0 - Shape Events fix [Part 1]

code/styles/Map.css
This PR is for....
* In the last PR the z-index was define with value 1, because the leaflet layers have values so high that overlaps the page content
* However the value 1 broke some samples, because it'll affect the siblings as well.
* ![image](https://user-images.githubusercontent.com/60441552/149571580-b0ad055a-0c91-40d4-86b9-779ceb91442c.png)
* redifine z-index to 0;
Since was a visual change:
- interact with markers, both providers;
- create 1 drawing tool and interact, google provider;
- create 1 marker and interact, both providers;
- create 1 marker popup and interact, both providers;
- interact with file layers, google provider;
- interact with heatmap, google provider;
- interact with marker clusterer, google provider;
=> Redefine z-index to 0

code/package.json, code/src/Providers/Leaflet/DrawingTools/DrawingTools.ts
This PR is for update the version of OutSystems Maps and fix an issue related with the update of Leaflet.Draw.
* Since we change the code to offer the OnDrawingChangeEvent it didn't work, because the plugin was returning duplicated coordinates (fixable with an update);
* After updating the Leaflet.Draw version we had an issue with circleMarker tool (that we have disabled by default), it starts to appear;
* Change the DrawingTools constructor with the right naming for circlemarker.
* Update version;
1. Use drawing tools, on a Leaflet map;
2. Use OnDrawingChange event;
3. Check if the coordinates returned are right;
=> ROU-3215 - [OSMaps] - Update Leaflet.Draw library to the latest version

code/src/Providers/Leaflet/Marker/Marker.ts
This PR is for adding an extra use-case for when the user does not input any height and width when using a icon url.
* custom icons that had no height or width specified were being drawn not certered on the actual coordinate.
* Added a promise to fetch the image's size before drawing it on the map.
=> ROU-3388 Update external icon position

code/src/OSFramework/DrawingTools/Factory.ts, code/src/OSFramework/Marker/Factory.ts, code/src/OSFramework/OSMap/Factory.ts, code/src/OSFramework/Shape/Factory.ts, code/src/OutSystems/Maps/MapAPI/Directions.ts, code/src/OutSystems/Maps/MapAPI/DrawingToolsManager.ts, code/src/Providers/Google/DrawingTools/Factory.ts, code/src/Providers/Google/Marker/Factory.ts, code/src/Providers/Google/OSMap/Factory.ts, code/src/Providers/Google/Shape/Factory.ts, code/src/Providers/Leaflet/Constants/Directions/TravelModes.ts, code/src/Providers/Leaflet/DrawingTools/Factory.ts, code/src/Providers/Leaflet/Marker/Factory.ts, code/src/Providers/Leaflet/OSMap/Factory.ts, code/src/Providers/Leaflet/Shape/Factory.ts
This PR is for a fix on Map directions not working properly because of namespace changes done in ROU-3077
* A side-effect of the work done in ROU-3077 we started having issues in the direction APIs where the method was calling the method GetTotalDistanceFromDirection instead of GetTotalDurationFromDirection
* The issue was introduced in this [commit](https://github.com/OutSystems/outsystems-maps/commit/74e9c6204176b58b075b5b99cfa2c1a3978b7461)
* Fixed the method name
* In the OutSystemsMaps module, replaced the namespace with OutSystems.Maps.MapAPI.* on all client actions  
1. Go to the test page
2. Add a start location and a destination
3. Click in Go
4. Check that the distances and time are according to the expected
* Before
* With the fix
=> Map directions not working properly

code/src/Providers/Leaflet/Marker/Marker.ts, code/src/Providers/Leaflet/OSMap/OSMap.ts
This PR is to fix Leaflet coordinates return on marker drag end.
* When using Marker's events on a Leaflet map and with drag end trigger, the coordinates were not being returned
* Changed the path on the event object that returns the LatLong coordinates 
1. Create a test screen with a Leaflet map
2. Add a marker
3. Set AllowDrag =True
4. Add the MarkerEvent block and set the trigger to Entities.MarkerEventTriggered.DragEnd
5. Changed the marker location and check that the coordinates are properly returned
=> Leaflet coordinates return on marker drag end

code/src/OSFramework/Event/AbstractEvent.ts, code/src/OSFramework/Event/AbstractEventsManager.ts, code/src/OSFramework/Event/OSMap/MapEventsManager.ts, code/src/OSFramework/Event/OSMap/MapProviderEvent.ts, code/src/OSFramework/Event/SearchPlaces/SearchPlacesEventsManager.ts, code/src/OSFramework/Helper/AsyncInvocation.ts, code/src/OutSystems/Maps/MapAPI/DrawingToolsManager.Events.ts, code/src/OutSystems/Maps/MapAPI/DrawingToolsManager.ts, code/src/OutSystems/Maps/MapAPI/FileLayerManager.Events.ts, code/src/OutSystems/Maps/MapAPI/MapManager.Events.ts, code/src/OutSystems/Maps/MapAPI/MarkerManager.Events.ts, code/src/OutSystems/Maps/MapAPI/ShapeManager.Events.ts, code/src/OutSystems/Maps/PlacesAPI/SearchPlacesManager.Events.ts
This PR is for fixing an issue related to the events destroying lifecycle.
* An error log was being fired every time we try to reach events that were destroyed. This was happening, for example, when we navigate really fast between pages, and the map was being built but the events blocks were already destroyed, the map finished its processes and called an event that already was destroyed.
* Create Handler Type;
* Change addHandler method;
* Change Event Managers;
* Clean eslint disable comments;
1. Navigate really fast between pages with events implemented;
2. Automated Tests;
=> ROU-3351 - [OSMaps] - Errors on the browser inspector's console and service center related to events

src/OSFramework/Maps/Event/OSMap/MapProviderEvent.ts
This PR fixes a bug where marker click event wasn't receiving correct coordinates.
* This was a side effect introduced in #104. We changed the coordinates parameter order.
* Adjusted the parameter order.
1. Click anywhere in the map.
Expected: A marker should be created on the place you clicked.
1. Open console
2. Press current screen button
Expected: No error should appear on console.
=> ROU-3687: Fixing marker on click

src/OSFramework/Maps/Event/DrawingTools/AbstractDrawingToolsEvent.ts, src/OSFramework/Maps/Event/FileLayer/AbstractFileLayersEvent.ts, src/OSFramework/Maps/Event/OSMap/MapEventsManager.ts, src/OSFramework/Maps/Feature/ICenter.ts, src/OSFramework/Maps/OSMap/IMap.ts, src/OutSystems/Maps/MapAPI/DrawingToolsManager.ts, src/OutSystems/Maps/MapAPI/FileLayerManager.ts, src/OutSystems/Maps/MapAPI/HeatmapLayerManager.ts, src/OutSystems/Maps/MapAPI/MapManager.ts, src/OutSystems/Maps/MapAPI/MarkerManager.ts, src/OutSystems/Maps/MapAPI/ShapeManager.Events.ts, src/OutSystems/Maps/MapAPI/ShapeManager.ts, src/OutSystems/Maps/PlacesAPI/SearchPlacesManager.ts, src/Providers/Maps/Google/Configuration/MarkerClusterer/MarkerClustererConfig.ts, src/Providers/Maps/Google/DrawingTools/AbstractProviderTool.ts, src/Providers/Maps/Google/DrawingTools/DrawMarker.ts, src/Providers/Maps/Google/Features/Center.ts, src/Providers/Maps/Google/Features/Directions.ts, src/Providers/Maps/Google/Features/FeatureBuilder.ts, src/Providers/Maps/Google/Features/Offset.ts, src/Providers/Maps/Google/Helper/Conversions.ts
This PR is for show a warning when the location given to a marker returns zero results from Geocode API.
* The marker was not appearing in some cases where the location given was not a valid address
* Added a console warning when zero results return from Geocode API.
* Changed the markers' location in samples.
1. Change the marker location to "OutSystems US". The console should display a warning.
2. Change the marker location to "55 Thomson Pl 2nd floor, Boston, MA 02210, United States". The marker should appear.
3. Change the marker location to "42.351639, -71.046770". The marker should appear.
=> ROU-3692: Google Maps Marker doesn't appear in some samples

src/Providers/Maps/Leaflet/Marker/Marker.ts, src/Providers/Maps/Leaflet/OSMap/OSMap.ts
This PR is for fixing an issue related with the map event.
* The map events were not returning coordinates when were supposed to.  
* Change the validation path.
1. Add a map event like click, rightclick or doubleClick;
2. Check if the event is returning coordinates;
=> ROU-3820v2 - [OSMaps][Leaflet] - Map Event On Zoom Changed is not returning the coordinates 

src/Providers/Maps/Google/Marker/Marker.ts
This PR is for fixing a issue related to the initial attributes of the marker;
* The marker was not respecting the width and height on the build method, those were just used on the change property
* call _setIconSize() on the build;
1. Add an icon with an image url and IconSize filled with a default value
2. Add two inputs to change the width and height
3. Check if the marker appears with the correct size
4. Change the variables using the inputs
5. Check if the marker is updated according to the new values
=> ROU-4001 - [OSMaps] - Marker icon size not working properly when marker is built

src/OSFramework/Maps/Event/DrawingTools/DrawingToolsProviderEvent.ts, src/OSFramework/Maps/Event/Shape/ShapeProviderEvent.ts, src/OSFramework/Maps/OSStructures/OSMap.Coordinates.ts, src/OSFramework/Maps/Shape/AbstractShape.ts, src/Providers/Maps/Google/DrawingTools/AbstractDrawShape.ts, src/Providers/Maps/Google/Shape/AbstractProviderShape.ts, src/Providers/Maps/Google/Shape/Circle.ts, src/Providers/Maps/Google/Shape/Polygon.ts, src/Providers/Maps/Google/Shape/Polyline.ts, src/Providers/Maps/Google/Shape/Rectangle.ts, src/Providers/Maps/Leaflet/DrawingTools/AbstractDrawShape.ts, src/Providers/Maps/Leaflet/Shape/AbstractProviderShape.ts, src/Providers/Maps/Leaflet/Shape/Circle.ts, src/Providers/Maps/Leaflet/Shape/Polygon.ts, src/Providers/Maps/Leaflet/Shape/Polyline.ts, src/Providers/Maps/Leaflet/Shape/Rectangle.ts
This PR is for fix the updated coordinates not being passed to the OnDrawChange event.
* It didn't exist a method o get the updated shape coordinates.
* The updated coordinates were not being passed as an argument to the ShapeProviderEvent.
* Created the getShapeProperties method for all shapes. This method returns the updated shape coordinates.
* In ShapeProviderEvent: Added an argument to trigger method to pass the updated shape coordinates.
* In AbstractDrawShape: Modified the _setOnChangeEvent method to pass the updated shape coordinates when triggering the DrawingToolsEvent.
* In AbstractProviderEvent: 
* Created the _triggerShapeChangedEvent method that get the updated shape coordinates and trigger the Shape event. 
* In the _buildProvider method, passed the …
=> ROU-4222: DrawCircle AddOn does not pass coordinates when editing a shape

styles/Map.css
Added CSS class `.runtime-staticMap-container-hide` into the block Map.css
* To be compliant with Content Security Policy (CSP) requirements, the support for inline styles will be discontinued. Consequently, this code will be impacted and may not function as expected.
It's important to note that this change will only affect those who need to ensure compliance with CSP guidelines.
* In order to anticipate impacts, we replaced the only usage of inline style by creating a CSS class to replace it.
1. Go to `OSMapsAutomation/MapsStatic`
2. Click on “Show Map“
3. Check that the Static Map is working as it was
=> ROU-4469: Update Map.css

src/OSFramework/Maps/DrawingTools/IDrawingToolsEventParams.ts, src/OSFramework/Maps/Event/FileLayer/FileLayersEventsManager.ts, src/OSFramework/Maps/Event/SearchPlaces/SearchPlacesEventsManager.ts, src/OSFramework/Maps/FileLayer/IFileLayerEventParams.ts, src/OSFramework/Maps/SearchPlaces/AbstractSearchPlaces.ts, src/OSFramework/Maps/SearchPlaces/ISearchPlacesEventParams.ts, src/Providers/Maps/Google/DrawingTools/AbstractDrawShape.ts, src/Providers/Maps/Google/FileLayer/FileLayer.ts, src/Providers/Maps/Google/SearchPlaces/SearchPlaces.ts
This PR is for missing types to the events of the Maps.
* Previously, some of the events, were accessing to the args in a given position to obtain certain values. This made the code harder to maintain and more error prone.
* Added 3 new interfaces:
* IDrawingToolsEventParams
* IFileLayerEventParams
* ISearchPlacesEventParams
* Created a new input parameter in the trigger action of:
* DrawingTools
* FileLayer
* SearchPlaces
* Set the interfaces as the type of the invocation of the trigger method
* [x tested locally
=> ROU-4375: Add types to events

.vscode/settings.json, src/Providers/Maps/Google/Features/Center.ts, src/Providers/Maps/Google/Helper/Conversions.ts, src/Providers/Maps/Google/Marker/Marker.ts, src/Providers/Maps/Google/Shape/AbstractPolyshape.ts, src/Providers/Maps/Google/Shape/Circle.ts, src/Providers/Maps/Google/Shape/Rectangle.ts, src/Providers/Maps/Google/SharedComponents/MapsAndSearchPlaces.ts
This PR is for changing the way addresses are transformed into coordinates.
The transformation of the addresses, was using a google REST API, that implied making a fetch in the maps code. Additionally there were situations in which the translation of the addresses failed.
* Change the code to start using the method `geo.geocode`, available out of the box in the Google Maps script.
* Scenario 1
* Open the screen
* Click on the button Go to map
* Click on the toggle above the map
* First time the map will disappear
* Second time the map will re-appear, but now running the new code
* Start typing Rua de Santa Maria in the OutSystems Search Places
* Notice that the map has changed the center of it
(The current code, **fails** to change the center of the map).
=> ROU-4591: change how addresses are transformed into coordenates

src/OSFramework/Maps/Helper/IsValidNumber.ts, src/Providers/Maps/Google/Marker/Marker.ts
This PR is for fixing an issue that was occurring when providing icon and icon size to each, causing what appeared to be imprecision when clicking on the marker. 
This issue was initially reported in [OutSystems community](https://www.outsystems.com/forums/discussion/91716/outsystems-maps-marker-popup-issue-on-phone/), by [Walter Robins](https://www.outsystems.com/profile/ithrqirw96/overview), that kindly provided a sample, and a good analysis of the issue - greatly contributing to finding the issue.
* when custom icon and the size (width and height) were set into a marker, the click on the marker became imprecise, occasionally, specially with many marker imprecise, opening sometimes the wrong pop-up.
* When creating the instance of `new google.maps.Size()` the type of the input affects …
=> ROU-4592: fixing google maps imprecision with markers

src/OSFramework/Maps/Configuration/IConfigurationMap.ts, src/OSFramework/Maps/Enum/OS_Config_Map.ts, src/OSFramework/Maps/OSMap/AbstractMap.ts, src/Providers/Maps/Google/Configuration/OSMap/GoogleMapConfig.ts, src/Providers/Maps/Google/OSMap/OSMap.ts, src/Providers/Maps/Leaflet/Configuration/OSMap/LeafletMapConfiguration.ts, src/Providers/Maps/Leaflet/Constants/OSMap/Events.ts, src/Providers/Maps/Leaflet/OSMap/OSMap.ts
This PR is adding the capacity for the map to respect the user changes on the zoom, when map center is changed, or markers are added, changed, removed. 
* The zoom was being reset whenever any change to the map that caused a refresh in it occurred.
* The scenarios when the reset occurred were:
* the center of the map changed (and there were no markers)
* the center of a marker changed
* a marker was added
* a marker was removed
* Added new optional config in the map: `RespectUserZoom` (default: false - current behavior)
* Added listener to zoom_changed (google maps) / zoom_end (leaflet) event
* Added flag to understand when the user scrolls `_zoomChanged`
* Blocked refreshZoom when `RespectUserZoom` config and `_zoomChanged` flag are set to true
1. Automatic tests were created
=> ROU-4665: allow preserving the zoom level when user changes it

.vscode/settings.json, src/OSFramework/Maps/Feature/IMarkerClusterer.ts, src/OSFramework/Maps/Helper/Constants.ts, src/OSFramework/Maps/Marker/AbstractMarker.ts, src/OutSystems/Maps/MapAPI/MapManager.ts, src/Providers/Maps/Google/Configuration/MarkerClusterer/MarkerClustererConfig.ts, src/Providers/Maps/Google/Features/GoogleMarkerClusterer.ts, src/Providers/Maps/Google/Features/InfoWindow.ts, src/Providers/Maps/Google/Global.d.ts, src/Providers/Maps/Google/Marker/Marker.ts, src/Providers/Maps/Google/Marker/MarkerPopup.ts, src/Providers/Maps/Google/OSMap/OSMap.ts, src/Providers/Maps/Google/SearchPlaces/SearchPlaces.ts, src/Providers/Maps/Google/SharedComponents/MapsAndSearchPlaces.ts, src/Providers/Maps/Leaflet/Marker/Marker.ts, src/Providers/Maps/Leaflet/Marker/MarkerPopup.ts, src/Providers/Maps/Leaflet/OSMap/OSMap.ts
This PR is in the continuation of previous PR, which introduced some issues, now solved. Additionally more fixes were added.
* When the back button is used, and the previous page has a list records with markers, the markers are first build then destroyed then built again... And when Addresses are passed, what happened was that the FinishBuild was ran after the dispose, causing a glitch in the number of markers per cluster.
* There was a console warning from google: `Google Maps JavaScript API has been loaded directly without loading=async. This can result in suboptimal performance. For best-practice loading patterns please see https://goo.gle/js-api-loading`
* I previous PR, the choice of map center was changed, leading to the marker being always chosen. 
* Added the protected attribute …
=> ROU-4709: Fixing cluster problems with back-button, other improvements

src/Global.d.ts, src/Providers/Maps/Google/Features/GoogleMarkerClusterer.ts
=> Fix lint issues at main branch

src/OSFramework/Maps/OSMap/AbstractMap.ts
This PR is for fixing an issue when the change property is triggered to update the values on parameters when is an object
* The parameters Offset and Localization are not being properly treated as an object and not properly set to the provider
* Added a typeof validation on changeProperty method to check if the propertyName on configs is an Object
=> ROU-4864: Offset and Localization is not being properly treated as an object

src/Providers/Maps/Google/Marker/Marker.ts
This PR is to fix Google Maps custom markers with scaled sizes.
* Setting custom markers using URL and icon size being set, didn’t have the right behaviour (regression from v1.6.6) and the markers didn't appear properly:
* The Google Maps marker API on the OutSystems MAps implementation used in the method `_setIcon` is an object with an attribute `size` when it should use `scaledSize`.
* Also, the Google Maps API got changed and requires the attributes `anchor` and, for readability (not mandatory in this case), also the `origin` so the icon gets properly scaled. 
1. Create a test screen with two Maps using custom markers - one setting up the IconSize and the other without this structure filled in
2. Check that for both Maps we can properly see the Markers we just defined on the low code …
=> ROU-10780: fix Google Maps custom markers with scaled sizes

package.json
This PR is to rollback some dependencies since the docs generation started to fail: 
- rollback TypeScript version back to `v4.5.0`
- rollback typedoc version back to:
```
"typedoc": "^0.23.9",
"typedoc-plugin-merge-modules": "^4.0.1",
"typedoc-umlclass": "^0.7.0",
```
=> ROU-0: rollback TypeScript and type doc versions 

src/Providers/Maps/Leaflet/Features/Zoom.ts
This PR is for fixing the pan/zoom on the leaflet map when reacting to the markers update.
* When markers were added or deleted on the leaflet map, the autofit behavior was not happening as supposed
* Use SetView on refreshZoom to guarantee the center is the latest;
1. Go to the Sample
2. Add various icons and delete some of them
3. Check if the map reacts as expected
4. Toggle the "Respect user zoom"
5. Interact again with the markers and do some zooms
6. Check if the map reacts as expected
=> ROU-10685 - [OSMaps] - Leaflet misbehavior when changing marker location after zooming out with more than 2 markers

src/OSFramework/Maps/Feature/ICenter.ts, src/Providers/Maps/Leaflet/Features/Center.ts, src/Providers/Maps/Leaflet/OSMap/OSMap.ts
This PR is for fixing an issue that occurs when changing the location of a marker (with more also occurs), after zooming out.
* Misbehavior when changing marker location after zooming out
* Change leaflet refresh method to apply the zoom in the same method where the center is applied;
1.  Go to page do a zoom 
2. Change the Center/Marker position
3. Check if it pans as expected
=> ROU-4725: [OSMaps] - Leaflet misbehavior when changing marker location after zooming out

src/Providers/Maps/Leaflet/Features/Center.ts
* Make sure the current center is updated with the right coordinates, when they are calculated by the bounds.
=> ROU-10685_V2 - [OSMaps] - Leaflet misbehavior when changing marker location after zooming out with more than 2 markers

src/OSFramework/Maps/Constants.ts, src/OSFramework/Maps/Helper/Constants.ts, src/OSFramework/Maps/Helper/LocalStorage.ts, src/OSFramework/Maps/ProviderVersion.ts, src/OutSystems/Maps/MapAPI/LibraryVersioning.ts, src/Providers/Maps/Google/Constants/Constants.ts, src/Providers/Maps/Google/HeatmapLayer/HeatmapLayer.ts, src/Providers/Maps/Google/OSMap/OSMap.ts, src/Providers/Maps/Google/OSMap/StaticMap.ts, src/Providers/Maps/Google/SearchPlaces/SearchPlaces.ts, src/Providers/Maps/Google/SharedComponents/MapsAndSearchPlaces.ts, src/Providers/Maps/Google/Version/Version.ts, src/Providers/Maps/Leaflet/Constants/Constants.ts, src/Providers/Maps/Leaflet/DrawingTools/DrawingTools.ts, src/Providers/Maps/Leaflet/OSMap/OSMap.ts, src/Providers/Maps/Leaflet/Version/Version.ts
This PR is to add new APIs to allow changing the version of Google Maps. 
Google Maps scripts cannot be hosted, and need to be imported from their CDN. If a version is not specified Google loads always the most recent stable version of the library. This was causing errors or warnings to appear, as neither the OutSystems R&D nor the developer using the component, control when the update was done.
To avoid this problems, the version of the Google Maps scripts being loaded was locked to a specific version (currently 3.57).
* However the change, made that the code is locked to a specific version of Google Maps
* And the developer has no ability to change it
* New APIs were added to getting and changing the version of the provider that is loaded
* …
=> ROU-4776: adding ability to change google maps version

src/OSFramework/Maps/OSMap/IMap.ts, src/Providers/Maps/Google/Features/Center.ts, src/Providers/Maps/Google/OSMap/OSMap.ts, src/Providers/Maps/Leaflet/Features/Center.ts, src/Providers/Maps/Leaflet/OSMap/OSMap.ts
This PR is for fixing the center update when the map was panned or zoomed, and the markers were presented.
* The center parameter was not respected when the user used the leaflet map with markers.
* add a flag to refresh the center position if the user changes the center;
* Clean and normalize refresh function on both providers;
1. Go to the sample page, and use the different buttons to change the center; 
2. Interact with both maps and afterward with the buttons;
3. Check if the maps behave as expected;
=> ROU-11371: [OSMaps] - Leaflet center not working as expected

src/OSFramework/Maps/SearchPlaces/AbstractSearchPlaces.ts, src/Providers/Maps/Google/SearchPlaces/SearchPlaces.ts
This PR is for improve the google.places creation, by checking if config.uniqueId still exists before create provider.
* Validate the uniqueId saved in configs was not clean before reaching createProvider();
1. Go to sample
2. Destroy and Create places repeatedly when the page is rendering;
3. Check that there are no errors in console related with places uniqueId;
=> ROU-11587_V2: javaScript Causing Error Logs on Google Places

src/Providers/Maps/Leaflet/Configuration/Marker/LeafletMarkerConfig.ts
This PR is for fixing the input parameter type for the icon width and height.
* When using a marker with an icon, and passing the dimentions
* The units were being passed wrongly to the provider (in string instead of number):
* This cause the observed misbehave:
* Upon constructing the object `LeafletMarkerConfig`, the configs will now be forced to the right type:
* This corrected the misbehave:
1. Use the leaflet map
2. Add a marker
3. Add an icon url to the marker
4. Pass the width and height
5. Publish
6. Click on the marker
7. (The map should not change the center)
(prefer animated gif)
=> ROU-11589: Making sure parameters are of the right type

.github/workflows/build.yaml, .github/workflows/pre-release.yaml, .github/workflows/release.yaml
Adding event `synchronize` so that the PR related workflows, run every time the PR is open, reopen, or new commits added to it.
=> ROU-11492: adding synchronize PR event 

src/OSFramework/Maps/Helper/Constants.ts, src/OSFramework/Maps/SearchPlaces/AbstractSearchPlaces.ts, src/Providers/Maps/Google/SearchPlaces/SearchPlaces.ts, src/Providers/Maps/Google/SearchPlaces/SearchPlacesLegacy.ts
This PR is for adapt the code to the block name change. Small improvements
* The SearchPlaces block name was changed, and this caused a runtime error.
* Added a new constant with the legacy block name
* Cleaned objects in these classes
=> ROU-12041: Adapting to block name change
