CODEOWNERS

This is a repo, that was born from the hands of @tmbp95! And proves his dedication, hard work and **skills**. This could not be done, of course, without the right guidance of a *senior of seniors* - @bmartinho (not calling you *extremely* old!).
But time has come, for this *baby* to be taken care by other hands - but you both will always be its beloved parents!
Also welcome to @BenOsodrac, @bmarcelino-fe, @joanabpereira, @joselrio and of course @gnbm!
This being said, have the final honor to approve this PR @bmartinho and @tmbp95 !
Good riddance!

Changing code owners

---

code/src/LeafletProvider/DrawingTools/AbstractDrawShape.ts
code/src/LeafletProvider/DrawingTools/AbstractProviderTool.ts
code/src/LeafletProvider/DrawingTools/DrawCircle.ts
code/src/LeafletProvider/DrawingTools/DrawMarker.ts
code/src/LeafletProvider/DrawingTools/DrawRectangle.ts

This PR is for adding the functionality to return coordinates and locations when drawing shapes.
* Added methods to return coordinates & locations

Update Shapes to return coordinates and locations.

---

code/src/Providers/Leaflet/DrawingTools/DrawingTools.ts

This PR is for cleaning google references on leaflet file;

ROU-3394 - [OSMaps] - Google Maps APIs calls in the scope of Leaflet

---

code/src/Providers/Google/OSMap/OSMap.ts
code/src/Providers/Leaflet/OSMap/OSMap.ts

Fixed dispose on maps

---

code/src/OutSystems/Maps/MapAPI/MarkerManager.ts

This PR is for adding support to the GetMarkersById API to the markers draw by the DrawingTools

ROU-3576: Add draw markers support to getMarkerById API

---

src/OSFramework/Maps/Enum/ErrorCodes.ts
src/OutSystems/Maps/MapAPI/MarkerManager.ts

This PR will add the new RemoveMarkerFromCluster API method.
It will be available the **OutSystems.Maps.MapAPI.MarkerManager.RemoveMarkerFromCluster** namespace.

ROU-3194: [RemoveMarkerFromCluster] new API method.

---

azure-pipelines.yml
jobs/azure-pipelines-reactive.yml

ROU-3799 maps pipeline with tests

ROU-3799 maps pipeline with tests

---

src/Providers/Maps/Leaflet/Marker/Marker.ts
src/Providers/Maps/Leaflet/OSMap/OSMap.ts

This PR is for fixing the map events in leaflet. 
* All map events of Leaflet weren't working because the way we were validating if the coordinates exist.
* Fix getLatLng validation;
1. Add a map event to a Leaflet Map;
2. Test the event and the check if the output is the expected.

ROU-3820 - [OSMaps][Leaflet] - Map Event On Zoom Changed is not returning the coordinates

---

src/OSFramework/Maps/Enum/ErrorCodes.ts
src/OSFramework/Maps/Feature/ExposedFeatures.ts
src/OSFramework/Maps/Feature/IShape.ts
src/OSFramework/Maps/OSStructures/ReturnMessage.ts
src/OutSystems/Maps/MapAPI/ShapeManager.ts
src/Providers/Maps/Google/Features/FeatureBuilder.ts
src/Providers/Maps/Google/Features/Shape.ts
src/Providers/Maps/Leaflet/Features/FeatureBuilder.ts
src/Providers/Maps/Leaflet/Features/Shape.ts

This PR is for adding the ContainsLocation client action and API to OutSystems Maps, to check if a provided marker is inside of a shape. Please check the JIRA info for more information.

ROU-3211: Add ContainsLocation API feature to OutSystems Maps

---

src/OSFramework/Maps/Enum/ErrorCodes.ts

This PR is for update the error message for unsupported polyline "shape"

ROU-3211_1: Update Error message of Polyline

---

src/OSFramework/Maps/Enum/ErrorCodes.ts
src/OSFramework/Maps/Feature/ICenter.ts
src/OutSystems/Maps/MapAPI/MapManager.ts
src/Providers/Maps/Google/Features/Center.ts
src/Providers/Maps/Leaflet/Features/Center.ts

This PR is for adding the new feature to Maps, to get the map center and expose the coordinates. Please check the JIRA issue for more info.

ROU-3851: Add GetMapCenter feature to maps

---

package.json
src/OSFramework/Maps/Constants.ts

Raised version of OutSystems Maps

ROU-3985: Raised version of OutSystems Maps

---

package.json
src/OSFramework/Maps/Constants.ts

* Raised version of OutSystems Maps
* Update Constants.ts
* Update Constants.ts

ROU-3985: Raised version of OutSystems Maps rc1.6.3 (#122)

---

.vscode/settings.json
CODEOWNERS
jobs/azure-pipelines-reactive.yml
package.json
src/OSFramework/Maps/Constants.ts
src/Providers/Maps/Google/Marker/Marker.ts

This PR is to merge release 1.6.4

Merge release 1.6.4

---

src/Providers/Maps/Google/Global.d.ts
src/Providers/Maps/Google/SharedComponents/MapsAndSearchPlaces.ts

This PR is for fixing a behavior on the initialization of the google maps script. 
* When we were loading the google maps script the provider was triggering a warning on the console because we were not sending a callback on the src.
* add callback on the google map script to avoid warning on the console.
1. Add Google Maps to a screen;
2. Run the page and check if the map appears as expected;
3. Check console shows an error/warning saying "Loading the Google Maps API without a callback ..."
4. The console should not has this error;

ROU-4125 - [OSMaps] - GoogleAPI is not being properly defined

---

LICENSE
README.md
package.json

Added license BDS-3 to this repository

Added license BDS-3 to this repository

---

.vscode/settings.json
jobs/azure-pipelines-reactive.yml
package.json
src/OSFramework/Maps/Constants.ts
src/Providers/Maps/Google/Global.d.ts
src/Providers/Maps/Google/Marker/Marker.ts
src/Providers/Maps/Google/SharedComponents/MapsAndSearchPlaces.ts

This PR is to merge release 1.6.5.

Release 1.6.5

---

src/Providers/Maps/Google/Configuration/Shape/CircleShapeConfig.ts
src/Providers/Maps/Google/Configuration/Shape/RectangleShapeConfig.ts
src/Providers/Maps/Leaflet/Configuration/Shape/CircleShapeConfig.ts
src/Providers/Maps/Leaflet/Configuration/Shape/RectangleShapeConfig.ts

This PR is for removing merge messages left in the code, when the last rc was merged. Has no impact in runtime.

Fixing messages left from merge

---

src/Providers/Maps/Leaflet/OSMap/OSMap.ts

This PR is for reintroducing a fix done some time ago. The fix was lost due to potentially merge problems.

Fixing leaflet map event, location object

---

.eslintignore
.prettierignore
.snyk
package.json
src/OSFramework/Maps/Constants.ts

Updated Version 1.6.8 and added .snyk file

Updated Version 1.6.8 and added .snyk file

---

src/OSFramework/Maps/Constants.ts

This PR is to update to version 1.7.0

Update to version 1.7.0

---

.eslintignore
package.json
src/Providers/Maps/Leaflet/Constants/Marker/Events.ts
src/Providers/Maps/Leaflet/Constants/OSMap/Events.ts

This PR is for fixing the eslint commands that were not causing the desired effect.
* Standardizing lint commands and configs
* Fix the eslint config and package json files
* Run and fixed lint problems

Fix lint configs

---

src/Global.d.ts
src/Providers/Maps/Google/Features/GoogleMarkerClusterer.ts

Fix lint issues.

---

README.md
gulp/DefaultSpecs.js
package.json
src/OSFramework/Maps/Constants.ts

This PR will increase repo version.

ROU-11399: Increased version.

---

.github/os-git-actions/setup-gpg/action.yml
.github/os-git-actions/signed-commit/action.yml
.github/workflows/DevPR.yml
.github/workflows/PreRelease.yml

This PR is for adding small improvements on the github actions.
- The way the github actions were accessing to the secrets and passing as input parameter to other actions;
- The version of the external github action `actions/checkout`
- Now, github actions that require secrets access to them directly
- `actions/checkout` was standardized to v4
- Tested changes in the sandbox
-   [x] tested locally
-   [ ] documented the code
-   [ ] clean all warnings and errors of eslint
-   [ ] requires changes in OutSystems (if so, provide a module with changes)
-   [ ] requires new sample page in OutSystems (if so, provide a module with changes)

ROU-11456: Small improvements in pipelines

---

package.json

* Updated the version of the following dev dependencies:
* `"@types/leaflet-routing-machine": "^3.2.8"`
* `"@types/leaflet": "^1.9.16"`

ROU-11574: Update leaflet types

---

src/Providers/Maps/Google/Features/Directions.ts

This PR is for making sure that when a route is not found, that the appropriate error message is returned.

ROU-12040: Dealing with route not found
